[WIP]: Update color token
thegymnasium/gym-eleventy pull request #88
Opened 2024-10-28 16:21 UTC by jgagne

## What this PR does

- Updates button hovered/focused state color from gray (disabled) to a shade of blue 

### Visual Preview

- [Color tokens](https://toolness.github.io/accessible-color-matrix/?n=text&n=hovered%2Ffocused%20(current)&n=hovered%2Ffocused%20(proposed)&n=enabled&v=FFFFFF&v=444444&v=015894&v=0077C8)

**Before:**

![gym-hover-focus-color-token-before](https://github.com/user-attachments/assets/58887198-68c5-4f52-89e0-69cb8fe76997)

**After:**

![gym-hover-focus-color-token-after](https://github.com/user-attachments/assets/f87e4fde-2c54-4691-b60f-5d61dd0ed721)

2024-10-28 16:44 UTC, rediris commented on src/scss/mfe/learning/_buttons.scss
> +    border-color: (var(--primary-500));
This rule looks a little wonky...

2024-10-28 16:44 UTC, rediris commented on src/scss/mfe-discussions.scss
> +  color: var(--primary-500)
needs closing semicolon

2024-10-28 16:45 UTC, rediris commented on src/scss/mfe/_buttons.scss
> +    border-color: (var(--primary-500));
fix parentheses in line 42

2024-10-28 16:48 UTC, rediris commented on src/scss/mfe/_forms.scss
> +$background-color_9: rgba(var(--primary-500), 0.8); // transparent-ish primary color?
I can't remember - does this work? We might be able to use `hsla` instead...

I was thinking maybe we can create a new transparent color map specifically for this, but maybe it's beyond the scope of this update.

2024-10-28 16:49 UTC, rediris commented on src/scss/mfe/discussions/_default.scss
> +  text-decoration-color: var(--primary-500)4d;
This one was "broken" before this change - this color needs to be another transparent color..., but I have no idea where it's used.

2024-10-28 16:50 UTC, rediris commented on src/scss/mfe/discussions/_default.scss
> +  text-decoration-color: var(--primary-500)4d;
Another broken var.

2024-10-28 16:50 UTC, rediris commented on src/scss/mfe/discussions/_default.scss
> +  box-shadow: 0 0 0 1px var(--primary-500)80;
Another broken.

2024-10-28 16:51 UTC, rediris commented on src/scss/mfe/discussions/_default.scss
> +  background-color: var(--primary-500)80;
Another broken

2024-10-28 16:51 UTC, rediris commented on src/scss/mfe/discussions/_default.scss
> +  background-color: var(--primary-500)80;
Another broken

2024-10-28 16:51 UTC, rediris commented on src/scss/mfe/discussions/_default.scss
> +  background-color: var(--primary-500)80;
Another broken

2024-10-28 16:53 UTC, rediris commented on src/scss/mfe/learning/_learning-original.scss
> +  text-decoration-color: rgba(var(--primary-500), 80);
As above - I don't know if this works as expected...

2024-10-28 16:53 UTC, rediris commented on src/scss/mfe/learning/_learning-original.scss
> +  box-shadow: 0 0 0 1px var(--primary-500) 80;
broken rule

2024-10-28 16:53 UTC, rediris commented on src/scss/mfe/learning/_learning-original.scss
> +  box-shadow: 0 0 0 1px var(--primary-500) 80;
broken rule

2024-10-28 16:53 UTC, rediris commented on src/scss/mfe/learning/_learning-original.scss
> +  background-color: var(--primary-500) 80;
broken rule

2024-10-28 16:53 UTC, rediris commented on src/scss/mfe/learning/_learning-original.scss
> +  background-color: var(--primary-500) 80;
Another broken

2024-10-28 16:53 UTC, rediris commented on src/scss/mfe/learning/_learning-original.scss
> +  background-color: var(--primary-500) 80;
Another broken

2024-10-28 16:57 UTC, rediris requested changes
This looks really good, and I like the color changes.

I've annotated some broken rules (broken before your update) that all correspond to places where openedx use 8 digit hex rules to represent transparency. I think the best solution is for us to create a new transparency color map and generate hsla values from it. Alternately, save it for later in another ticket, assuming we can figure out a way to best document the broken rules.

Let me know your thoughts.

2024-10-28 16:57 UTC, rediris commented
> This looks really good, and I like the color changes.
> 
> I've annotated some broken rules (broken before your update) that all correspond to places where openedx use 8 digit hex rules to represent transparency. I think the best solution is for us to create a new transparency color map and generate hsla values from it. Alternately, save it for later in another ticket, assuming we can figure out a way to best document the broken rules.
> 
> Let me know your thoughts.

Oops - I didn't notice this was a WIP - sorry I jumped on this too soon.

2024-10-28 16:57 UTC, jgagne commented
@rediris — Thanks for the pre-review. Keep you posted on updates.

2024-11-18 21:00 UTC, rediris approved these changes
Let's do it!

2024-11-18 21:10 UTC, merged